# Generated by Django 5.0.7 on 2024-07-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
