# Generated by Django 4.2 on 2024-07-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
